### ISSUE TITLE
Cannot register on Asterisk

### ISSUE THREAD

**Issue by primoitt83** [DoubleBastionAdmin/roundpin#1]
Hi!

My Roundpin cannot register on Asterisk 18 LTS..

Its always complain about wrong password... but it is correct..

````
[2023-09-09 18:59:55] NOTICE[127]: res_pjsip/pjsip_distributor.c:676 log_failed_request: Request 'REGISTER' from '"1003" <sip:1003@mypbx.local>' failed for '192.168.48.2:43752' (callid: lf8ai5ej59hbr1i6bnlhot) - Failed to authenticate
<--- Transmitting SIP response (506 bytes) to WS:192.168.48.2:43752 --->
SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS 192.0.2.21;rport=43752;received=192.168.48.2;branch=z9hG4bK199641
Call-ID: lf8ai5ej59hbr1i6bnlhot
From: "1003" <sip:1003@mypbx.local>;tag=4hs8dmpg95
To: "1003" <sip:1003@mypbx.local>;tag=z9hG4bK199641
CSeq: 1914 REGISTER
WWW-Authenticate: Digest realm="mypbx.local",nonce="1694285995/0691c1e8ec35e0e7ea1b3f2c0f788df5",opaque="2335680f3191a431",algorithm=MD5,qop="auth"
Server: mypbx
Content-Length:  0
````
Tested on Browser phone and works fine..

https://github.com/InnovateAsterisk/Browser-Phone

**Comment by primoitt83** [comment]
On LocalStorage password looks like encrypted..

![roundpin](https://github.com/DoubleBastionAdmin/roundpin/assets/18406286/314f8bad-ad9c-4552-ba85-5a89e0b44491)

**Comment by DoubleBastionAdmin** [comment]
As shown [here](https://www.doublebastion.com/install-roundpin/#configure-nginx-for-roundpin) Roundpin has to be installed on a real subdomain, like `roundpin.example.com`, with proper A and AAAA DNS records, a TLS certificate has to be obtained for that subdomain, like the free certificate from Let's Encrypt, and the web server (Nginx), has to be configured to serve the application on the subdomain `roundpin.example.com`. It seems that you are using "mypbx.local", instead of a real subdomain. The authentication failure seems to be linked with this fact rather than with the way the password is handled. Roundpin has never been tested on locally created domains, without DNS records, like "mypbx.local". It may work with Browser Phone, but Roundpin is quite different. It has been heavily modified.

If you already have a real domain, like `example.com` you just have to add DNS records for the subdomain `roundpin` and then use `roundpin.example.com` to serve the application.

This being said, we are very close to releasing a new version of Roundpin (1.0.5), which has a huge number of improvements as compared to the old version. It has FAX, SMS, improved encrypted text chat and video conferences, etc. It will be a true self-hosted, free and open source replacement for Skype/Zoom. If you want to be on our newsletter just let us now at tech@doublebastion.com. This is how it looks when a registered user makes a phone call:

![new_roundpin](https://github.com/DoubleBastionAdmin/roundpin/assets/98547981/fc720be1-c39f-44a0-81b6-236c74e2f3bd)

**Comment by primoitt83** [comment]
Yeah... but "mypbx.local" is not my true domain..

I got a Letsencrypt certificate for domain and subdomain for Roundpin and Asterisk.. by the way both are behind the nginx reverve proxy (Nginx Proxy Manager) which takes care about webservices and certificates.

Is there any issue running this way?

**Comment by DoubleBastionAdmin** [comment]
So, you actually serve the application with Apache and use Nginx as a reverse proxy for SSL termination ?

**Comment by DoubleBastionAdmin** [comment]
If yes, then this is an untested setup. Roundpin is created as part of a specific setup which is the simplest and the most efficient. This setup involves Nginx as a web server and not as a reverse proxy. Apache is totally excluded.

By the way, for the authentication to work, you have to have a directory with a name identical with that of your Roundpin user, let's say `tom`, inside the `restr` directory. Inside the `restr/tom` directory, you have to have the file `pwdkey`, with the following ownership and permissions:
```
-rw------- 1 www-data www-data   80 Feb 28  2023 pwdkey
```
The SipPassword parameter from LocalStorage that you show above, `%20%20%20%20%20%20` is just a placeholder. It's neither the real password, nor its encrypted form.

**Comment by primoitt83** [comment]
> So, you actually serve the application with Apache and use Nginx as a reverse proxy for SSL termination ?

No.. both are Nginx.. there is no Apache

**Comment by primoitt83** [comment]
> If yes, then this is an untested setup. Roundpin is created as part of a specific setup which is the simplest and the most efficient. This setup involves Nginx as a web server and not as a reverse proxy. Apache is totally excluded.
> 
> By the way, for the authentication to work, you have to have a directory with a name identical with that of your Roundpin user, let's say `tom`, inside the `restr` directory. Inside the `restr/tom` directory, you have to have the file `pwdkey`, with the following ownership and permissions:
> 
> ```
> -rw------- 1 www-data www-data   80 Feb 28  2023 pwdkey
> ```
> 
> The SipPassword parameter from LocalStorage that you show above, `%20%20%20%20%20%20` is just a placeholder. It's neither the real password, nor its encrypted form.

humm.. my "restr" is empty

````
/html/roundpin/restr# ls -lah
total 8.0K
drwxr-xr-x  2 root root 4.0K Sep  2 21:53 .
drwxr-xr-x 11 root root 4.0K Sep  3 12:38 ..
-rw-r--r--  1 root root    0 Sep  2 21:53 .gitignore
````

**Comment by primoitt83** [comment]
Maybe all this happened cause I did a workaround to solve a issue when tryed to run this file:

roundpin/roundpin-setup.php

And php output show me:

```
WARNING: [pool www] child 76 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined variable: mysqli in /[app/roundpin/roundpin-initializedb.php](http://app/roundpin/roundpin-initializedb.php) on line 74"
`````
So my workaround was:

````
cat > test-roundpin-config.php 
<?php

// Create the configuration file

$dbname = 'roundpin';
$dbuser = 'roundpin';
$dbuserpswd = 'roundpin';

// $dbname = $_POST['databasename'];
// $dbuser = $_POST['databaseuser'];
// $dbuserpswd = $_POST['dbuserpassword'];

// Generate the secret
$keypassin = substr(sha1(mt_rand()), 0, 32);
$keysaltin = openssl_random_pseudo_bytes(24);
$keyLengthin = 80;
$iterationin = 100;
$generated_keyin = openssl_pbkdf2($keypassin, $keysaltin, $keyLengthin, $iterationin, 'sha256');
$keypwd = bin2hex($generated_keyin);

$texttofill = "<?php\r\nif(!defined('ACCESSCONST')){die();}\r\n\r\n\$databasename='".$dbname."';\r\n\$username='".$dbuser."';\r\n\$password='".$dbuserpswd."';\r\n\$secret='".$keypwd."';\r\n?>";

file_put_contents("roundpin-config.php", $texttofill);

?>
````

````
php -f test-roundpin-config.php
````

That generates the file roundpin-config.php..

Now I can access /roundpin/roundpin-setup.php and keep on configuration...

So my worikaound ruined everything?

**Comment by DoubleBastionAdmin** [comment]
> humm.. my "restr" is empty

If your `restr` directory is empty, that is what causes the authentication failure. The `restr/tom` directory and the `pwdkey` file inside it, should have been created the moment you saved the settings of Roundpin (after you clicked on the Settings wheel, then under 'Connection Settings' you entered the WebSocket domain, WebSocket Port, WebSocketPath, Display Name, SIP Username, and SIP Password, then clicked the 'Save' button).

Since your `restr` directory is empty, it seems that the web server user, `www-data` didn't have the right permissions to create the directory and file. Why is your `restr` directory owned by `root:root` ? It should be owned by `www-data:www-data`, like this:
```
drwxr-x---  6 www-data www-data  4096 Feb 13  2023 restr
```

**Comment by primoitt83** [comment]
> > humm.. my "restr" is empty
> 
> If your `restr` directory is empty, that is what causes the authentication failure. The `restr/tom` directory and the `pwdkey` file inside it, should have been created the moment you saved the settings of Roundpin (after you clicked on the Settings wheel, then under 'Connection Settings' you entered the WebSocket domain, WebSocket Port, WebSocketPath, Display Name, SIP Username, and SIP Password, then clicked the 'Save' button).
> 
> Since your `restr` directory is empty, it seems that the web server user, `www-data` didn't have the right permissions to create the directory and file. Why is your `restr` directory owned by `root:root` ? It should be owned by `www-data:www-data`, like this:
> 
> ```
> drwxr-x---  6 www-data www-data  4096 Feb 13  2023 restr
> ```


Ok.. I've changed the ownership and set permissions but my directory is still empty:

````
html/roundpin# ls -lah restr/
total 8.0K
drwxrwxr-x  2 www-data www-data 4.0K Sep  2 21:53 .
drwxrwxr-x 11 www-data www-data 4.0K Sep  3 12:38 ..
-rwxrwxr-x  1 www-data www-data    0 Sep  2 21:53 .gitignore
````
Im still thinking about my workaround destruction..

**Comment by primoitt83** [comment]
![image](https://github.com/DoubleBastionAdmin/roundpin/assets/18406286/3a7c5611-3c09-4505-b3c5-0c49163a0f61)

**Comment by DoubleBastionAdmin** [comment]
The PHP warning that you posted above is quite odd. It can be related to the PHP version and modules, MariaDB version, etc. On our server the installation worked without problems. You could read what error appears in the error log (`/var/log/nginx/roundpin.example.com.error.log`) when you click the 'Save' button on the Settings window. That is the moment when the `restr/tom/pwdkey` file has to be created.

To avoid losing time on debugging this issue maybe it would be better to try the next version of Roundpin, which contains numerous changes, including to the installation process.

**Comment by primoitt83** [comment]
It works now!

![image](https://github.com/DoubleBastionAdmin/roundpin/assets/18406286/1e034afb-405b-4e94-a37c-d659c0bc95e6)

**Comment by primoitt83** [comment]
You were right.... It was a permission problem.

In my case I've needed set permissions to user "application" who is running PHP process:

````
ps -aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         50  0.0  0.1 141260 11472 ?        S    Sep12   0:00 nginx: master process /usr/sbin/nginx -g daemon off;
root         51  0.0  0.4 711224 39544 ?        S    Sep12   0:02 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
root         52  0.0  0.0  30104  3168 ?        S    Sep12   0:00 /usr/sbin/cron -f
www-data     67  0.0  0.0 142052  7152 ?        S    Sep12   0:00 nginx: worker process
www-data     68  0.0  0.0 141664  6512 ?        S    Sep12   0:00 nginx: worker process
www-data     69  0.0  0.0 141596  5312 ?        S    Sep12   0:00 nginx: worker process
www-data     70  0.0  0.0 141596  3748 ?        S    Sep12   0:00 nginx: worker process
www-data     71  0.0  0.0 141596  3748 ?        S    Sep12   0:00 nginx: worker process
www-data     72  0.0  0.0 141596  3748 ?        S    Sep12   0:00 nginx: worker process
www-data     73  0.0  0.0 141596  3748 ?        S    Sep12   0:00 nginx: worker process
www-data     75  0.0  0.0 141596  3748 ?        S    Sep12   0:00 nginx: worker process
applica+     76  0.0  0.3 713844 28452 ?        S    Sep12   0:00 php-fpm: pool www
applica+     77  0.0  0.3 713844 28272 ?        S    Sep12   0:00 php-fpm: pool www
root       2214  0.0  0.0  20356  3748 pts/0    Ss   14:50   0:00 /bin/bash
root       2225  0.0  0.0  36152  3224 pts/0    R+   14:55   0:00 ps -aux
````
````
cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/usr/share/nginx/html/:/bin/bash
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
application:x:1000:1000::/home/application:/bin/bash
````
````
cd html
chown application.1000 -R roundpin/
chmod 775 -R roundpin/
````
Thx for help me out!
